Crie uma lista do Python que contenha 10 inteiros aleatórios (entre 0 e 100). Em seguida, a partir da lista criada anteriormente, crie um array do Numpy, utilizando a função array.

In [2]:
import numpy as np
import random as rd

lista = []

for i in range(10):
    lista.append(rd.randint(0, 100))
    
vetor = np.array(lista)
vetor

array([ 7, 33,  3, 50, 32,  4, 93, 14,  7, 68])

Crie um array com 10 elementos (iniciando em zero), em que os elementos tenham um intervalo de 3 unidades entre si.

In [2]:
inicio = 0

elementos = 10

intervalo = 3

np.arange(inicio, inicio + intervalo*elementos, intervalo)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Crie um array com 40 elementos entre 0 e π.



In [3]:
import math as mt

pi40 = np.linspace(0, mt.pi, 40)
pi40

array([0.        , 0.08055366, 0.16110732, 0.24166097, 0.32221463,
       0.40276829, 0.48332195, 0.5638756 , 0.64442926, 0.72498292,
       0.80553658, 0.88609024, 0.96664389, 1.04719755, 1.12775121,
       1.20830487, 1.28885852, 1.36941218, 1.44996584, 1.5305195 ,
       1.61107316, 1.69162681, 1.77218047, 1.85273413, 1.93328779,
       2.01384144, 2.0943951 , 2.17494876, 2.25550242, 2.33605608,
       2.41660973, 2.49716339, 2.57771705, 2.65827071, 2.73882436,
       2.81937802, 2.89993168, 2.98048534, 3.061039  , 3.14159265])

Crie um array com 40 elementos, todos iguais a 6.

In [4]:
seis = np.full(40, 6)
seis 

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])